services:
  postgres:
    image: postgres:15-alpine
    container_name: order_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: order_kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data

  init-kafka:
    image: apache/kafka:latest
    container_name: init_kafka
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # Ждем стартовую готовность брокера
      sleep 3;
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic order.events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1;
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic payment.events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1;
      "

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: order_service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    container_name: notification_service
    environment:
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    depends_on:
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    container_name: payment_service
    environment:
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    depends_on:
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully

  frontend:
    build: ./web
    container_name: order_web
    ports:
      - "80:80"
    depends_on:
      - order-service

volumes:
  postgres_data:
  kafka_data:
